version: "3.1"
services:
  nies:
    build:
      context: .
      dockerfile: Dockerfile
    image: nepolin/pression_index_streamlit:latest
    command: bash
    volumes:
      - $PWD:/workdir
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nepolin/pression_index_streamlit:latest
    entrypoint: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    volumes:
      - $PWD:/workdir
    ports:
      - "8501:8501"